<?php
/**
 * Apiv1paymentcreateShippingDetails
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Axerve-php
 *
 * Axerve API client made for PHP
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Apiv1paymentcreateShippingDetails Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Apiv1paymentcreateShippingDetails implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'apiv1paymentcreate_shippingDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ship_to_zip' => 'string',
'ship_to_street2' => 'string',
'ship_to_country_code' => 'string',
'ship_to_name' => 'string',
'ship_to_street' => 'string',
'ship_to_state' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ship_to_zip' => null,
'ship_to_street2' => null,
'ship_to_country_code' => null,
'ship_to_name' => null,
'ship_to_street' => null,
'ship_to_state' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ship_to_zip' => 'shipToZip',
'ship_to_street2' => 'shipToStreet2',
'ship_to_country_code' => 'shipToCountryCode',
'ship_to_name' => 'shipToName',
'ship_to_street' => 'shipToStreet',
'ship_to_state' => 'shipToState'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ship_to_zip' => 'setShipToZip',
'ship_to_street2' => 'setShipToStreet2',
'ship_to_country_code' => 'setShipToCountryCode',
'ship_to_name' => 'setShipToName',
'ship_to_street' => 'setShipToStreet',
'ship_to_state' => 'setShipToState'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ship_to_zip' => 'getShipToZip',
'ship_to_street2' => 'getShipToStreet2',
'ship_to_country_code' => 'getShipToCountryCode',
'ship_to_name' => 'getShipToName',
'ship_to_street' => 'getShipToStreet',
'ship_to_state' => 'getShipToState'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ship_to_zip'] = isset($data['ship_to_zip']) ? $data['ship_to_zip'] : null;
        $this->container['ship_to_street2'] = isset($data['ship_to_street2']) ? $data['ship_to_street2'] : null;
        $this->container['ship_to_country_code'] = isset($data['ship_to_country_code']) ? $data['ship_to_country_code'] : null;
        $this->container['ship_to_name'] = isset($data['ship_to_name']) ? $data['ship_to_name'] : null;
        $this->container['ship_to_street'] = isset($data['ship_to_street']) ? $data['ship_to_street'] : null;
        $this->container['ship_to_state'] = isset($data['ship_to_state']) ? $data['ship_to_state'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ship_to_zip
     *
     * @return string
     */
    public function getShipToZip()
    {
        return $this->container['ship_to_zip'];
    }

    /**
     * Sets ship_to_zip
     *
     * @param string $ship_to_zip ship_to_zip
     *
     * @return $this
     */
    public function setShipToZip($ship_to_zip)
    {
        $this->container['ship_to_zip'] = $ship_to_zip;

        return $this;
    }

    /**
     * Gets ship_to_street2
     *
     * @return string
     */
    public function getShipToStreet2()
    {
        return $this->container['ship_to_street2'];
    }

    /**
     * Sets ship_to_street2
     *
     * @param string $ship_to_street2 ship_to_street2
     *
     * @return $this
     */
    public function setShipToStreet2($ship_to_street2)
    {
        $this->container['ship_to_street2'] = $ship_to_street2;

        return $this;
    }

    /**
     * Gets ship_to_country_code
     *
     * @return string
     */
    public function getShipToCountryCode()
    {
        return $this->container['ship_to_country_code'];
    }

    /**
     * Sets ship_to_country_code
     *
     * @param string $ship_to_country_code ship_to_country_code
     *
     * @return $this
     */
    public function setShipToCountryCode($ship_to_country_code)
    {
        $this->container['ship_to_country_code'] = $ship_to_country_code;

        return $this;
    }

    /**
     * Gets ship_to_name
     *
     * @return string
     */
    public function getShipToName()
    {
        return $this->container['ship_to_name'];
    }

    /**
     * Sets ship_to_name
     *
     * @param string $ship_to_name ship_to_name
     *
     * @return $this
     */
    public function setShipToName($ship_to_name)
    {
        $this->container['ship_to_name'] = $ship_to_name;

        return $this;
    }

    /**
     * Gets ship_to_street
     *
     * @return string
     */
    public function getShipToStreet()
    {
        return $this->container['ship_to_street'];
    }

    /**
     * Sets ship_to_street
     *
     * @param string $ship_to_street ship_to_street
     *
     * @return $this
     */
    public function setShipToStreet($ship_to_street)
    {
        $this->container['ship_to_street'] = $ship_to_street;

        return $this;
    }

    /**
     * Gets ship_to_state
     *
     * @return string
     */
    public function getShipToState()
    {
        return $this->container['ship_to_state'];
    }

    /**
     * Sets ship_to_state
     *
     * @param string $ship_to_state ship_to_state
     *
     * @return $this
     */
    public function setShipToState($ship_to_state)
    {
        $this->container['ship_to_state'] = $ship_to_state;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
