<?php
/**
 * Apiv1paymentcreateShippingDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Axerve\Client
 * @author   Axerve Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Axerve-php
 *
 * Axerve API client made for PHP
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Axerve Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Axerve\Client;

/**
 * Apiv1paymentcreateShippingDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description Apiv1paymentcreateShippingDetails
 * @package     Axerve\Client
 * @author      Axerve Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Apiv1paymentcreateShippingDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Apiv1paymentcreateShippingDetails"
     */
    public function testApiv1paymentcreateShippingDetails()
    {
    }

    /**
     * Test attribute "ship_to_zip"
     */
    public function testPropertyShipToZip()
    {
    }

    /**
     * Test attribute "ship_to_street2"
     */
    public function testPropertyShipToStreet2()
    {
    }

    /**
     * Test attribute "ship_to_country_code"
     */
    public function testPropertyShipToCountryCode()
    {
    }

    /**
     * Test attribute "ship_to_name"
     */
    public function testPropertyShipToName()
    {
    }

    /**
     * Test attribute "ship_to_street"
     */
    public function testPropertyShipToStreet()
    {
    }

    /**
     * Test attribute "ship_to_state"
     */
    public function testPropertyShipToState()
    {
    }
}
