<?php
/**
 * Apiv1paymentsubmitPaymentTypeDetailsCreditcardTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Axerve\Client
 * @author   Axerve Codegen team
 * @link     https://github.com/axerve-api/axerve-codegen
 */

/**
 * Axerve-php
 *
 * Axerve API client made for PHP
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/axerve-api/axerve-codegen.git
 * Axerve Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the axerve code generator program.
 * https://github.com/axerve-api/axerve-codegen
 * Please update the test case below to test the model.
 */

namespace Axerve\Client;

use PHPUnit\Framework\TestCase;

/**
 * Apiv1paymentsubmitPaymentTypeDetailsCreditcardTest Class Doc Comment
 *
 * @category    Class
 * @description Apiv1paymentsubmitPaymentTypeDetailsCreditcard
 * @package     Axerve\Client
 * @author      Axerve Codegen team
 * @link        https://github.com/axerve-api/axerve-codegen
 */
class Apiv1paymentsubmitPaymentTypeDetailsCreditcardTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Apiv1paymentsubmitPaymentTypeDetailsCreditcard"
     */
    public function testApiv1paymentsubmitPaymentTypeDetailsCreditcard()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "exp_month"
     */
    public function testPropertyExpMonth()
    {
    }

    /**
     * Test attribute "cvv"
     */
    public function testPropertyCvv()
    {
    }

    /**
     * Test attribute "exp_year"
     */
    public function testPropertyExpYear()
    {
    }

    /**
     * Test attribute "dcc"
     */
    public function testPropertyDcc()
    {
    }

    /**
     * Test attribute "request_token"
     */
    public function testPropertyRequestToken()
    {
    }
}
