<?php
/**
 * Apiv1paymentcreatePaymentChannelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Axerve\Client
 * @author   Axerve Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Axerve-php
 *
 * Axerve API client made for PHP
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Axerve Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Axerve\Client;

/**
 * Apiv1paymentcreatePaymentChannelTest Class Doc Comment
 *
 * @category    Class
 * @description Apiv1paymentcreatePaymentChannel
 * @package     Axerve\Client
 * @author      Axerve Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Apiv1paymentcreatePaymentChannelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Apiv1paymentcreatePaymentChannel"
     */
    public function testApiv1paymentcreatePaymentChannel()
    {
    }

    /**
     * Test attribute "channel_type"
     */
    public function testPropertyChannelType()
    {
    }
}
