<?php
/**
 * Apiv1paymentsubmitResponseURLsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Axerve\Client
 * @author   Axerve Codegen team
 * @link     https://github.com/axerve-api/axerve-codegen
 */

/**
 * Axerve-php
 *
 * Axerve API client made for PHP
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/axerve-api/axerve-codegen.git
 * Axerve Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the axerve code generator program.
 * https://github.com/axerve-api/axerve-codegen
 * Please update the test case below to test the model.
 */

namespace Axerve\Client;

use PHPUnit\Framework\TestCase;

/**
 * Apiv1paymentsubmitResponseURLsTest Class Doc Comment
 *
 * @category    Class
 * @description Apiv1paymentsubmitResponseURLs
 * @package     Axerve\Client
 * @author      Axerve Codegen team
 * @link        https://github.com/axerve-api/axerve-codegen
 */
class Apiv1paymentsubmitResponseURLsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Apiv1paymentsubmitResponseURLs"
     */
    public function testApiv1paymentsubmitResponseURLs()
    {
    }

    /**
     * Test attribute "buyer_ko"
     */
    public function testPropertyBuyerKo()
    {
    }

    /**
     * Test attribute "buyer_ok"
     */
    public function testPropertyBuyerOk()
    {
    }

    /**
     * Test attribute "server_notification_url"
     */
    public function testPropertyServerNotificationUrl()
    {
    }
}
