<?php
/**
 * Body3Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Axerve\Client
 * @author   Axerve Codegen team
 * @link     https://github.com/axerve-api/axerve-codegen
 */

/**
 * Axerve-php
 *
 * Axerve API client made for PHP
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/axerve-api/axerve-codegen.git
 * Axerve Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the axerve code generator program.
 * https://github.com/axerve-api/axerve-codegen
 * Please update the test case below to test the model.
 */

namespace Axerve\Client;

use PHPUnit\Framework\TestCase;

/**
 * Body3Test Class Doc Comment
 *
 * @category    Class
 * @description Body3
 * @package     Axerve\Client
 * @author      Axerve Codegen team
 * @link        https://github.com/axerve-api/axerve-codegen
 */
class Body3Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Body3"
     */
    public function testBody3()
    {
    }

    /**
     * Test attribute "payment_type_details"
     */
    public function testPropertyPaymentTypeDetails()
    {
    }

    /**
     * Test attribute "response_ur_ls"
     */
    public function testPropertyResponseUrLs()
    {
    }

    /**
     * Test attribute "shop_login"
     */
    public function testPropertyShopLogin()
    {
    }

    /**
     * Test attribute "payment_type"
     */
    public function testPropertyPaymentType()
    {
    }

    /**
     * Test attribute "buyer"
     */
    public function testPropertyBuyer()
    {
    }
}
