<?php
/**
 * InlineResponse2001PayloadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Axerve-php
 *
 * Axerve API client made for PHP
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse2001PayloadTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2001Payload
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2001PayloadTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2001Payload"
     */
    public function testInlineResponse2001Payload()
    {
    }

    /**
     * Test attribute "payment_token"
     */
    public function testPropertyPaymentToken()
    {
    }

    /**
     * Test attribute "payment_id"
     */
    public function testPropertyPaymentId()
    {
    }

    /**
     * Test attribute "user_redirect"
     */
    public function testPropertyUserRedirect()
    {
    }
}
