<?php
/**
 * PaymentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Axerve\Client
 * @author   Axerve Codegen team
 * @link     https://github.com/axerve-api/axerve-codegen
 */

/**
 * Axerve-php
 *
 * Axerve API client made for PHP
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/axerve-api/axerve-codegen.git
 * Axerve Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the axerve code generator program.
 * https://github.com/axerve-api/axerve-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Axerve\Client;

use Axerve\Client\Configuration;
use Axerve\Client\ApiException;
use Axerve\Client\ObjectSerializer;

/**
 * PaymentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Axerve\Client
 * @author   Axerve Codegen team
 * @link     https://github.com/axerve-api/axerve-codegen
 */
class PaymentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiV1CheckCreditCardPost
     *
     * .
     *
     */
    public function testApiV1CheckCreditCardPost()
    {
    }

    /**
     * Test case for apiV1PaymentCancelPost
     *
     * .
     *
     */
    public function testApiV1PaymentCancelPost()
    {
    }

    /**
     * Test case for apiV1PaymentCapturePost
     *
     * .
     *
     */
    public function testApiV1PaymentCapturePost()
    {
    }

    /**
     * Test case for apiV1PaymentCreatePost
     *
     * .
     *
     */
    public function testApiV1PaymentCreatePost()
    {
    }

    /**
     * Test case for apiV1PaymentMethodsPaymentIdLanguageIdGet
     *
     * .
     *
     */
    public function testApiV1PaymentMethodsPaymentIdLanguageIdGet()
    {
    }

    /**
     * Test case for apiV1PaymentRefundPost
     *
     * .
     *
     */
    public function testApiV1PaymentRefundPost()
    {
    }

    /**
     * Test case for apiV1PaymentSubmitPost
     *
     * .
     *
     */
    public function testApiV1PaymentSubmitPost()
    {
    }

    /**
     * Test case for apiV1PaymentUpdatePost
     *
     * .
     *
     */
    public function testApiV1PaymentUpdatePost()
    {
    }

    /**
     * Test case for apiV1ShopMethodsShopLoginGet
     *
     * .
     *
     */
    public function testApiV1ShopMethodsShopLoginGet()
    {
    }
}
